### ISSUE TITLE
Profiles don't work in Android 5.1

### ISSUE THREAD

**Issue by vibinr** [marshall/logcat-color#17]
So I updated to 5.1 and failed to get logcat-color working properly. I did no changes to the config (stored at ~/.logcat-color).

It contains

`Profile(name = "billy",
    packages = [ "com.vibin.billy" ]
)`

If I just type logcat-color, it'll output the log fine, so the issue is only with profiles.
Thanks.

**Comment by vibinr** [comment]
pidcat has been updated with a fix. https://github.com/JakeWharton/pidcat/issues/92

**Comment by marshall** [comment]
Thanks for the heads up! I'll try to get the fix in soon

**Comment by fentie** [comment]
https://github.com/marshall/logcat-color/pull/25
